<?php

include_once('chargify_sites.features.inc');

/**
 * Implementation of hook_init().
 */
function chargify_sites_init() {
  drupal_add_css(drupal_get_path('module', 'chargify_sites') .'/chargify_sites.css');
}

/**
 * Implementation of hook_menu().
 */
function chargify_sites_menu() {
  $items = array();

  $items['admin/settings/chargify-sites'] = array(
    'title' => 'Chargify Sites',
    'description' => 'Configure settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('chargify_sites_settings_form'),
    'access arguments' => array('administer chargify sites'),
    'file' => 'chargify_sites.pages.inc',
  );

  $items['new-site/%chargify_sites_product'] = array(
    'title' => 'New Subscription',
    'title callback' => 'chargify_sites_product_title',
    'title arguments' => array(1),
    'page callback' => 'chargify_sites_new_site_page',
    'page arguments' => array(1),
    'access arguments' => array('create site content'),
    'file' => 'chargify_sites.pages.inc',
  );

  $items['new-site/%node/time-to-pay'] = array(
    'title' => 'Payment',
    'title callback' => 'chargify_sites_payment_page_title',
    'title arguments' => array(1),
    'description' => 'Configure settings',
    'page callback' => 'chargify_sites_payment_page',
    'page arguments' => array(1),
    'access callback' => 'chargify_sites_payment_page_access',
    'access arguments' => array(1),
    'file' => 'chargify_sites.pages.inc',
  );

  return $items;
}

/**
 * Loads up a product by handle from Chargify.
 */
function chargify_sites_product_load($handle) {
  $product = chargify_api_product_get($handle, 'handle');
  return is_object($product) ? $product : FALSE;
}

/**
 * Return a product title.
 */
function chargify_sites_product_title($product) {
  return t($product->getName());
}

/**
 * Alter the payment page title.
 */
function chargify_sites_payment_page_title($node) {
  return t('Time to pay for !title', array('!title' => $node->title));
}

/**
 * Provide access for the payment page.
 */
function chargify_sites_payment_page_access($node, $account = NULL) {
  global $user;
  $account = is_null($account) ? $user : $account;
  return ($node->uid == $account->uid);
}

/**
 * Implementation of hook_perm().
 */
function chargify_sites_perm() {
  return array('administer chargify sites');
}

/**
 * Implementation of hook_nodeapi().
 */
function chargify_sites_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == 'site') {
    switch ($op) {
      case 'insert':
        $_REQUEST['destination'] = 'new-site/'. $node->nid .'/time-to-pay';
      case 'update':
        if (isset($node->subscription->subscription_id)) {
          chargify_sites_node_save($node);
        }
        break;
      case 'load':
        return chargify_sites_node_load($node);
      case 'view':
        if (isset($node->subscription) && $output = theme('chargify_subscription_state', $node->subscription->state)) {
          $weight = content_extra_field_weight($node->type, 'chargify_sites');

          $node->content['chargify_sites'] = array(
            '#weight' => !empty($weight) ? $weight : -10,
            '#value' => $output,
          );
        }
        $teaser = $a3;
        $page = $a4;
        if (!$teaser && $page) {
          drupal_set_breadcrumb(array(l(t('My sites'), 'my-sites')));
        }
        break;
      case 'delete':
        chargify_sites_node_delete($node);
        break;
    }
  }
}

/**
 * Implementation of hook_theme().
 */
function chargify_sites_theme() {
  $items = array();

  $items['chargify_sites_product_page'] = array(
    'arguments' => array('product' => NULL),
    'template' => 'chargify-sites-product-page',
  );

  return $items;
}

/**
 * Implementation of hook_strongarm().
 */
function chargify_sites_strongarm() {
  return array(
    'ant_site' => 1,
    'ant_pattern_site' => '[field_domain-url]',
    'user_email_verification' => FALSE,
    'pathauto_node_site_pattern' => 'my-sites/[title-raw]',
  );
}

/**
 * Implementation of hook_content_extra_fields().
 */
function chargify_sites_content_extra_fields() {
  $extras['chargify_sites'] = array(
    'label' => t('Subscription Status'),
    'description' => t('Chargify subscription status fieldset.'),
    'weight' => -10,
  );

  return $extras;
}

/**
 * Implementation of hook_form_alter().
 */
function chargify_sites_form_site_node_form_alter(&$form, $form_state) {
  $form['buttons']['preview']['#access'] = FALSE;
  $form['buttons']['submit']['#value'] = t('Continue');
}

/**
 * Set some theme settings. Called by _webgear_feature_enable().
 */
function chargify_sites_theme_settings() {
  return array(
    'toggle_node_info_site' => 0,
  );
}

/**
 * Implementation of hook_preprocess_chargify_sites_product_page().
 */
function chargify_sites_preprocess_chargify_sites_product_page(&$vars) {
  drupal_add_js(drupal_get_path('module', 'chargify_sites') .'/fancyForm.js');

  global $user;
  $product = $vars['product'];

  module_load_include('inc', 'node', 'node.pages');
  $node_type = 'site';
  $node = array('uid' => $user->uid, 'name' => (isset($user->name) ? $user->name : ''), 'type' => $node_type, 'language' => '');
  $vars['form_output'] = drupal_get_form($node_type .'_node_form', $node);

  $vars['price'] = theme('chargify_product_price', $product);

  // Convert line breaks into p tags.
  $text = _filter_autop($product->description);
  $vars['description'] = t($text);
}

/**
 * Helper function to save a node.
 */
function chargify_sites_node_save(&$node) {
  $record = array('nid' => $node->nid, 'subscription_id' => $node->subscription->subscription_id);

  // Check to see if we're updating.
  if (db_result(db_query("SELECT COUNT(*) FROM {chargify_sites} WHERE nid = %d", $node->nid)) > 0) {
    drupal_write_record('chargify_sites', $record, array('subscription_id'));
  }
  // Otherwise, write a new row.
  else {
    drupal_write_record('chargify_sites', $record);
  }
}

/**
 * Helper function to process loading a node.
 */
function chargify_sites_node_load(&$node) {
  $ret = array();

  $sql = "SELECT * FROM {chargify_subscriptions} sub INNER JOIN {chargify_sites} site ON sub.subscription_id = site.subscription_id WHERE site.nid = %d";
  if ($subscription = db_fetch_object(db_query($sql, $node->nid))) {
    $ret['subscription'] = $subscription;
  }

  return $ret;
}

/**
 * Helper function to save a node.
 */
function chargify_sites_node_delete(&$node) {
  if (isset($node->subscription->subscription_id)) {
    chargify_subscription_delete_record($node->subscription->subscription_id);
    db_query("DELETE FROM {chargify_sites} WHERE nid = %d", $node->nid);
  }
}