<?php

include_once('chargify_sites.features.inc');

/**
 * Implementation of hook_enable().
 */
function chargify_sites_enable() {
  if (function_exists('path_set_alias')) {
    path_set_alias('node/add/site', 'new-site');
  }
}

/**
 * Implementation of hook_menu().
 */
function chargify_sites_menu() {
  $items = array();

  $items['admin/settings/chargify-sites'] = array(
    'title' => 'Chargify Sites',
    'description' => 'Configure settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('chargify_sites_settings_form'),
    'access arguments' => array('administer chargify sites'),
    'file' => 'chargify_sites.pages.inc',
  );

  $items['new-site/time-to-pay/%node'] = array(
    'title' => 'Payment',
    'title callback' => 'chargify_sites_payment_page_title',
    'title arguments' => array(2),
    'description' => 'Configure settings',
    'page callback' => 'chargify_sites_payment_page',
    'page arguments' => array(2),
    'access arguments' => array('create site content'),
    'file' => 'chargify_sites.pages.inc',
  );

  $items['new-site/paid/%node'] = array(
    'title' => 'Thanks!',
    'description' => 'Configure settings',
    'page callback' => 'chargify_sites_paid_page',
    'page arguments' => array(2),
    'access arguments' => array('create site content'),
    'file' => 'chargify_sites.pages.inc',
  );

  return $items;
}

function chargify_sites_payment_page_title($node) {
  return t('Time to pay for !title', array('!title' => $node->title));
}

/**
 * Implementation of hook_perm().
 */
function chargify_sites_perm() {
  return array('administer chargify sites');
}

/**
 * Implementation of hook_nodeapi().
 */
function chargify_sites_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == 'site' && $path = variable_get('chargify_sites_payment_page_hosted_path', '')) {
    switch ($op) {
      case 'insert':
        $_REQUEST['destination'] = 'new-site/time-to-pay/'. $node->nid;
        break;
    }
  }
}

function chargify_sites_strongarm() {
  return array(
    'ant_site' => 1,
    'ant_pattern_site' => '[field_domain-url]',
  );
}
